import fs from 'fs';
import path from 'path';
import { Window } from 'happy-dom';

import { beforeEach, it, vi } from 'vitest';
import {} from './';

const docPath = path.join(process.cwd(), 'index.html');
const docContent = fs.readFileSync(docPath).toString();

const window = new Window();
const document = window.document;

vi.stubGlobal('document', document);

beforeEach(() => {
  document.body.innerHTML = '';
  document.write(docContent);
});

describe('Search Address div', () => {
  it('Div should display error message in case of errors.', () => {
    // Arrange ...
    // Act ...
    // Assert ...
  });

  it('Address should be the same as input value.', () => {
    // Arrange ...
    // Act ...
    // Assert ...
  });

  it('Balance should display a value in ETH.', () => {
    // Arrange ...
    // Act ...
    // Assert ...
  });
});

describe('Transaction div', () => {
  it('Should initially be invisible', () => {
    // Arrange ...
    // Act ...
    // Assert ...
  });

  it('Should display the same values as the inputs after sending a transaction.', () => {
    // Arrange ...
    // Act ...
    // Assert ...
  });

  it('Send more than you have displays error message.', () => {
    // Arrange ...
    // Act ...
    // Assert ...
  });

  it('Transaction failing should display an error message.', () => {
    // Arrange ...
    // Act ...
    // Assert ...
  });
});
